[[plugins]]
repo = 'arcticicestudio/nord-vim'
on_event = 'ColorSchemePre'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_source = '''
    let g:lexima_map_escape = ''

    " <> rules for vim and toml
        call lexima#add_rule({ 'char': '<', 'input': '<', 'input_after': '>', 'filetype': ['vim', 'toml'] })
        call lexima#add_rule({ 'char': '>', 'at': '\%#>', 'leave': 1, 'filetype': ['vim', 'toml'] })
        call lexima#add_rule({ 'char': '<BS>', 'at': '<\%#>', 'input': '<BS>', 'delete' : 1, 'filetype': ['vim', 'toml'] })

    " Python f string
        call lexima#add_rule({ 'char': "'", 'at': 'f\%#', 'input': "'", 'input_after': "'", 'filetype': 'python' })
'''

