" vim .vimrc

language C

set encoding=utf-8
set fileencoding=utf-8

set nocompatible
set nobackup
set noswapfile

syntax enable
filetype indent plugin on

colorscheme slate

" Edit

set number

set autoread
set hidden

set autoindent
set shiftround

set smarttab
set expandtab
set shiftwidth=4
set tabstop=4

set splitbelow
set splitright

set list
set listchars=tab:>\ ,trail:-

set backspace=indent,eol,start

inoremap jk <ESC>

nnoremap x "_x
vnoremap x "_x

nmap q <NOP>

" Statusline

set laststatus=2
set ruler

" Command

set wildmenu
set wildoptions=pum

set showcmd

" Search

set incsearch
set hlsearch
set smartcase
set ignorecase

set shortmess-=S " Show match counts

" General

set belloff=all

set clipboard=unnamed,unnamedplus

" Save last cursor position
autocmd BufRead * if line("'\"") > 0 && line("'\"") <= line("$") | exe "normal g`\"" | endif

let g:did_menu_trans            = 1
let g:did_install_default_menus = 1
let g:skip_loading_mswin        = 1
let g:did_install_syntax_menu   = 1

let g:loaded_gzip               = 1
let g:loaded_man                = 1
let g:loaded_matchit            = 1
let g:loaded_netrwPlugin        = 1
let g:loaded_shada_plugin       = 1
let g:loaded_spellfile_plugin   = 1
let g:loaded_tarPlugin          = 1
let g:loaded_2html_plugin       = 1
let g:loaded_tutor_mode_plugin  = 1
let g:loaded_zipPlugin          = 1

