" dein.vim

set runtimepath+=~/.cache/dein/repos/github.com/Shougo/dein.vim

if dein#min#load_state('~/.cache/dein')
    call dein#begin('~/.cache/dein')
        call dein#load_toml('~/.config/vim/dein.toml'     , { 'lazy': 0 })
        call dein#load_toml('~/.config/vim/dein_lazy.toml', { 'lazy': 1 })
    call dein#end()
    call dein#save_state()
endif

if dein#check_install()
    call dein#install()
endif

" vim .vimrc

set encoding=utf-8

set nocompatible
set nobackup
set noswapfile

syntax enable
filetype indent plugin on

" Colors

colorscheme evening

if exists('+termguicolors')
   set termguicolors
endif

if exists('$TMUX')
    let &t_8f = "\<Esc>[38:2:%lu:%lu:%lum"
    let &t_8b = "\<Esc>[48:2:%lu:%lu:%lum"
endif

" Edit

set number

set autoread
set hidden

set autoindent
set smartindent

set smarttab
set expandtab
set shiftwidth=4
set tabstop=4

set list
set listchars=tab:>\ ,trail:-

set backspace=indent,eol,start

inoremap jk <ESC>

nnoremap x "_x
vnoremap x "_x

" Statusline

set laststatus=2
set ruler

set showtabline=2

" Command

if exists('+wildmenu')
    set wildmenu
endif

if exists('+wildignore')
    set wildoptions=pum
endif

set showcmd

" Search

set incsearch
set hlsearch
set smartcase
set ignorecase

set shortmess-=S " Show match counts

" General

set mouse=a
set belloff=all

set clipboard=unnamedplus

set shellslash

" cursor shapes
if has('vim_starting')
    let &t_SI .= "\e[6 q"
    let &t_EI .= "\e[2 q"
    let &t_SR .= "\e[4 q"
endif

let g:did_menu_trans            = 1
let g:did_install_default_menus = 1
let g:skip_loading_mswin        = 1
let g:did_install_syntax_menu   = 1

let g:loaded_gzip               = 1
let g:loaded_man                = 1
let g:loaded_matchit            = 1
let g:loaded_netrwPlugin        = 1
let g:loaded_shada_plugin       = 1
let g:loaded_spellfile_plugin   = 1
let g:loaded_tarPlugin          = 1
let g:loaded_2html_plugin       = 1
let g:loaded_tutor_mode_plugin  = 1
let g:loaded_zipPlugin          = 1

