# ===========================================================================
#
#   dein.vim dein_lazy.toml
#
# ===========================================================================

# =================================================
[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'williamboman/nvim-lsp-installer'
on_event = 'BufRead'
depends = ['nvim-lspconfig', 'cmp-nvim-lsp']
hook_source = '''
    source ~/.config/nvim/plugins/lsp.lua
'''

[[plugins]]
repo = 'jose-elias-alvarez/null-ls.nvim'
on_event = 'BufRead'
hook_source = '''
lua << EOF
    local null_ls = require('null-ls')
    local sources = {
        null_ls.builtins.formatting.autopep8,
    }

    null_ls.setup({ sources = sources })
EOF
'''

# =================================================
[[plugins]]
repo = 'hrsh7th/nvim-cmp'
on_event = 'InsertEnter'
hook_source = '''
    source ~/.config/nvim/plugins/cmp.lua
'''

[[plugins]]
repo = 'hrsh7th/cmp-buffer'
on_source = ['nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-nvim-lsp'
on_source = ['nvim-cmp']

[[plugins]]
repo = 'hrsh7th/cmp-vsnip'
on_source = ['nvim-cmp']
depends = ['vim-vsnip']

[[plugins]]
repo = 'hrsh7th/vim-vsnip'
hook_source = '''
    " Jump forward
    imap <expr> <C-j> vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<C-j>'
    smap <expr> <C-j> vsnip#jumpable(1)  ? '<Plug>(vsnip-jump-next)' : '<C-j>'

    " Jump backward
    imap <expr> <C-k> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-k>'
    smap <expr> <C-k> vsnip#jumpable(-1) ? '<Plug>(vsnip-jump-prev)' : '<C-k>'
'''

# =================================================
[[plugins]]
repo = 'nvim-telescope/telescope.nvim'
on_event = 'BufEnter'
depends = ['plenary.nvim', 'nvim-web-devicons']
hook_source = '''
    source ~/.config/nvim/plugins/telescope.lua
'''

[[plugins]]
repo = 'nvim-lua/plenary.nvim'

[[plugins]]
repo = 'kyazdani42/nvim-web-devicons'

# =================================================
[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = 'BufRead'

# =================================================
[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'
hook_source = '''
    let g:lexima_map_escape = ''

    " <> rules for vim and toml
    call lexima#add_rule({ 'char': '<', 'input': '<', 'input_after': '>', 'filetype': ['vim', 'toml'] })
    call lexima#add_rule({ 'char': '>', 'at': '\%#>', 'leave': 1, 'filetype': ['vim', 'toml'] })
    call lexima#add_rule({ 'char': '<BS>', 'at': '<\%#>', 'input': '<BS>', 'delete' : 1, 'filetype': ['vim', 'toml'] })

    " Python f string
    call lexima#add_rule({ 'char': "'", 'at': 'f\%#', 'input': "'", 'input_after': "'", 'filetype': 'python' })
'''

# =================================================
[[plugins]]
repo = 'airblade/vim-gitgutter'
on_event = 'BufRead'
hook_source = '''
    set updatetime=500
    let g:gitgutter_map_keys = 0
'''

