# ===========================================================================
#
#   dein.vim dein.toml
#
# ===========================================================================

# =================================================
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
    let g:dein#auto_recache = !has('win32')
'''

# =================================================
[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
    let g:edge_better_performance = 1
    let g:edge_transparent_background = 1
    let g:edge_disable_italic_comment = 1
'''

# =================================================
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set noshowmode
    let g:lightline = {}
    let g:lightline.colorscheme = 'edge'
    let g:lightline.separator = { 'left': "\ue0b0", 'right': "\ue0b2" }
    let g:lightline.subseparator = { 'left': "\ue0b1", 'right': "\ue0b3" }
'''

# =================================================
[[plugins]]
repo = 'nathom/filetype.nvim'
hook_add = '''
    let g:did_load_filetypes = 1
'''

# =================================================
[[plugins]]
repo = 'tpope/vim-fugitive'

