# ===========================================================================
#
#   dein.vim dein.toml
#
# ===========================================================================

# =================================================
[[plugins]]
repo = 'Shougo/dein.vim'
hook_add = '''
    let g:dein#auto_recache = !has('win32')
'''

# =================================================
[[plugins]]
repo = 'lewis6991/impatient.nvim'
hook_add = '''
lua << EOF
    require('impatient').enable_profile()
EOF
'''

# =================================================
[[plugins]]
repo = 'itchyny/lightline.vim'
depends = 'vim-gitbranch'
hook_add = '''
    set noshowmode
    let g:lightline = {}
    let g:lightline.enable = { 'statusline': 1, 'tabline': 1 }

    let g:lightline.colorscheme = 'edge'
    let g:lightline.separator = { 'left': "\ue0b0", 'right': "\ue0b2" }
    let g:lightline.subseparator = { 'left': "\ue0b1", 'right': "\ue0b3" }
    let g:lightline.active = { 'left': [ ['mode', 'paste'], ['gitbranch', 'readonly', 'filename', 'modified'] ] }
    let g:lightline.component_function = { 'gitbranch': 'Branch' }

    function Branch() abort
        let l:current_branch = gitbranch#name() 
        return !empty(current_branch) ? "\ue725 ".current_branch : ''
    endfunction
'''

[[plugins]]
repo = 'itchyny/vim-gitbranch'
on_func = 'gitbranch#name()'
