# =================================================
[[plugins]]
repo = 'sainnhe/edge'
hook_add = '''
    let g:edge_better_performance = 1
    colorscheme edge
'''

# =================================================
[[plugins]]
repo = 'itchyny/lightline.vim'
hook_add = '''
    set noshowmode
    let g:lightline = {}
    let g:lightline.colorscheme = 'edge'
    let g:lightline.separator = { 'left': "\ue0b4", 'right': "\ue0b6" }
    let g:lightline.subseparator = { 'left': "\ue0b5", 'right': "\ue0b7" }
'''

# =================================================
[[plugins]]
repo = 'machakann/vim-sandwich'
on_event = 'BufRead'

[[plugins]]
repo = 'cohama/lexima.vim'
on_event = 'InsertEnter'

# =================================================
[[plugins]]
repo = 'ctrlpvim/ctrlp.vim'
on_cmd = 'CtrlP'
hook_add = '''
    nnoremap <c-p> <cmd>CtrlP<cr>
'''
hook_source = '''
    let g:ctrlp_max_depth = 10
    let g:ctrlp_max_files = 5000
'''

# =================================================
[[plugins]]
repo = 'voldikss/vim-floaterm'
on_cmd = 'FloatermToggle'
hook_add = '''
    nnoremap T <cmd>FloatermToggle<CR>
'''
hook_source = '''
    au TermClose * call feedkeys('')
    au FileType floaterm nnoremap <buffer> <esc> <cmd>FloatermToggle<cr>
'''

# =================================================
[[plugins]]
repo = 'dstein64/vim-startuptime'
on_cmd = 'StartupTime'

